### ISSUE TITLE
how pass proxy use ?

### ISSUE THREAD

**Issue by sertubon** [angelobelchior/FCM.Net#17]
System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=An error occurred while sending the request.
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FCM.Net.Sender.<SendAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FCM.Net.Sender.<SendAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Pwa8CRM.frmInfomation.<bntSentMessage_ClickAsync>d__10.MoveNext() in D:\SourceCodeTest\Pwa8CRM\Pwa8CRM\frmInfomation.cs:line 128

Inner Exception 1:
WebException: The remote server returned an error: (407) Proxy Authentication Required.

how pass proxy use ?

**Comment by sertubon** [comment]
How do I use a Proxy ?
